const $=s=>document.querySelector(s),home=$('#home'),reader=$('#reader'),image=$('#quranImage'),preview=$('#previewImage'),pageSurface=$('#swipeArea'),pageElement=$('#quranPage'),nf=new Intl.NumberFormat('ar-EG'),STORAGE='https://firebasestorage.googleapis.com/v0/b/ihfad-2fecd.firebasestorage.app/o/';
const SURAH_NAMES=['','الفاتحة','البقرة','آل عمران','النساء','المائدة','الأنعام','الأعراف','الأنفال','التوبة','يونس','هود','يوسف','الرعد','إبراهيم','الحجر','النحل','الإسراء','الكهف','مريم','طه','الأنبياء','الحج','المؤمنون','النور','الفرقان','الشعراء','النمل','القصص','العنكبوت','الروم','لقمان','السجدة','الأحزاب','سبأ','فاطر','يس','الصافات','ص','الزمر','غافر','فصلت','الشورى','الزخرف','الدخان','الجاثية','الأحقاف','محمد','الفتح','الحجرات','ق','الذاريات','الطور','النجم','القمر','الرحمن','الواقعة','الحديد','المجادلة','الحشر','الممتحنة','الصف','الجمعة','المنافقون','التغابن','الطلاق','التحريم','الملك','القلم','الحاقة','المعارج','نوح','الجن','المزمل','المدثر','القيامة','الإنسان','المرسلات','النبأ','النازعات','عبس','التكوير','الانفطار','المطففين','الانشقاق','البروج','الطارق','الأعلى','الغاشية','الفجر','البلد','الشمس','الليل','الضحى','الشرح','التين','العلق','القدر','البينة','الزلزلة','العاديات','القارعة','التكاثر','العصر','الهمزة','الفيل','قريش','الماعون','الكوثر','الكافرون','النصر','المسد','الإخلاص','الفلق','الناس'];
const AYAH_COUNTS=[0,7,286,200,176,120,165,206,75,129,109,123,111,43,52,99,128,111,110,98,135,112,78,118,64,77,227,93,88,69,60,34,30,73,54,45,83,182,88,75,85,54,53,89,59,37,35,38,29,45,60,49,62,55,78,96,29,22,24,13,14,11,11,18,12,12,30,52,52,44,28,28,20,56,40,31,50,40,46,42,29,19,36,25,22,17,30,19,15,21,11,8,8,19,5,8,8,11,11,8,3,9,5,4,7,3,9,5,4,7,6,3,5,4,5,6];
let currentPage=1,gesture=null,selectedAyah=null,playQueue=[],playIndex=0,audioMode='full';
function imgURL(p){let f=`quran-pages/page-${String(PAGE_MAP[p-1].pdfPage).padStart(3,'0')}.jpg`;return `${STORAGE}${encodeURIComponent(f)}?alt=media`;}function audioKey(k){let [s,a]=k.split(':').map(Number);return String(s).padStart(3,'0')+String(a).padStart(3,'0');}function fbAudio(k){return `${STORAGE}${encodeURIComponent(`audio/husary-muallim-128/${audioKey(k)}.mp3`)}?alt=media`;}function sourceAudio(k){return `https://everyayah.com/data/Husary_Muallim_128kbps/${audioKey(k)}.mp3`;}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600);}function showLoader(t,m,p=0,eta='يرجى الانتظار'){$('#loadingTitle').textContent=t;$('#loadingMessage').textContent=m;$('#loadingPercent').textContent=`${nf.format(p)}٪`;$('#loadingEta').textContent=eta;$('#loadingProgress').style.width=`${p}%`;$('#loadingOverlay').classList.add('show');}function hideLoading(){$('#loadingOverlay').classList.remove('show');}
function updateInfo(){let m=PAGE_MAP[currentPage-1],s=Number(m.verses[0][0].split(':')[0]);$('#surahLabel').textContent=`سورة ${SURAH_NAMES[s]}، صفحة ${nf.format(currentPage)}`;$('#pageSelect').value=currentPage;}
function renderPage(loader=false){selectedAyah=null;$('#ayahSelection').hidden=true;updateInfo();if(loader)showLoader('جاري الانتقال',`يتم تجهيز الصفحة ${nf.format(currentPage)} من المصحف الشريف`,100,'لحظات قليلة');let done=()=>hideLoading();image.addEventListener('load',done,{once:true});image.addEventListener('error',()=>{hideLoading();toast('تعذر تحميل الصفحة.');},{once:true});image.src=imgURL(currentPage);if(image.complete&&image.naturalWidth)done();}
function resetSwipe(){pageElement.classList.remove('is-dragging');image.style.transform='';preview.style.transform='';preview.classList.remove('visible');gesture=null;}function settleSwipe(){let {delta,width,target,direction}=gesture;if(Math.abs(delta)<=width*.18)return resetSwipe();pageElement.classList.remove('is-dragging');image.style.transform=`translateX(${direction*width}px)`;preview.style.transform='translateX(0)';setTimeout(()=>{currentPage=target;image.src=preview.src;updateInfo();resetSwipe();},285);}
function openMenu(){$('#sideMenu').classList.add('open');$('#overlay').classList.add('open');}function closeMenu(){$('#sideMenu').classList.remove('open');$('#overlay').classList.remove('open');}function showReader(){home.classList.add('hidden');reader.classList.remove('hidden');renderPage();}function showHome(){reader.classList.add('hidden');home.classList.remove('hidden');closeMenu();stopAudio();}
function selectAyah(y){let verses=PAGE_MAP[currentPage-1].verses,index=Math.max(0,Math.min(verses.length-1,Math.floor(((y/pageElement.clientHeight)-.08)/.84*verses.length)));selectedAyah=verses[index][0];let box=$('#ayahSelection');box.style.top=`${Math.max(58,Math.min(pageElement.clientHeight-45,y-17))}px`;box.hidden=false;}async function copyAyah(){if(!selectedAyah)return;let[s,a]=selectedAyah.split(':');try{await navigator.clipboard.writeText(`سورة ${SURAH_NAMES[s]}، الآية ${a}`);toast('تم نسخ مرجع الآية.');}catch{toast(`الآية ${nf.format(a)} من سورة ${SURAH_NAMES[s]}`);}}
function updateAudio(){let k=playQueue[playIndex],[s,a]=k.split(':');$('#audioAyahLabel').textContent=`سورة ${SURAH_NAMES[s]} — الآية ${nf.format(a)}`;$('#audioPlayer').classList.remove('hidden');}function loadAudio(k,fallback=true){let a=$('#quranAudio');updateAudio();a.src=fbAudio(k);a.play().catch(()=>{if(fallback){a.src=sourceAudio(k);a.play().catch(()=>toast('تعذر تشغيل الصوت حالياً.'));}});}function playKeys(k){if(!k.length)return;playQueue=k;playIndex=0;loadAudio(k[0]);}function stopAudio(){let a=$('#quranAudio');a.pause();a.removeAttribute('src');a.load();playQueue=[];$('#audioPlayer').classList.add('hidden');}
function populateAyahs(s){let f=$('#fromAyah');f.innerHTML='';for(let a=1;a<=AYAH_COUNTS[s];a++)f.add(new Option(`الآية ${nf.format(a)}`,a));updateToAyahs();}function updateToAyahs(){let s=+$('#surahSelect').value,f=+$('#fromAyah').value,t=$('#toAyah');t.innerHTML='';for(let a=f+1;a<=AYAH_COUNTS[s];a++)t.add(new Option(`الآية ${nf.format(a)}`,a));t.disabled=!t.options.length;}
for(let p=1;p<=604;p++)$('#pageSelect').add(new Option(`الصفحة ${nf.format(p)}`,p));for(let s=1;s<=114;s++)$('#surahSelect').add(new Option(`${nf.format(s)} — سورة ${SURAH_NAMES[s]}`,s));populateAyahs(1);
$('#readButton').onclick=showReader;$('#memorizeButton').onclick=()=>toast('قسم التحفيظ سيكون الخطوة التالية بإذن الله.');$('#backButton').onclick=showHome;$('#menuButton').onclick=openMenu;$('#closeMenu').onclick=closeMenu;$('#overlay').onclick=closeMenu;$('#goToPage').onclick=()=>{currentPage=+$('#pageSelect').value;closeMenu();renderPage(true);};$('#openListening').onclick=()=>{$('#mainMenu').classList.add('hidden');$('#listeningMenu').classList.remove('hidden');};$('#backToMenu').onclick=()=>{$('#listeningMenu').classList.add('hidden');$('#mainMenu').classList.remove('hidden');};$('#surahSelect').onchange=e=>populateAyahs(+e.target.value);$('#fromAyah').onchange=updateToAyahs;document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{audioMode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));$('#rangeFields').classList.toggle('hidden',audioMode==='full');});$('#playSelection').onclick=()=>{let s=+$('#surahSelect').value,f=audioMode==='full'?1:+$('#fromAyah').value,t=audioMode==='full'?AYAH_COUNTS[s]:+$('#toAyah').value;if(audioMode==='range'&&!t)return toast('اختر الآية التي تريد التوقف عندها.');closeMenu();playKeys(Array.from({length:t-f+1},(_,i)=>`${s}:${f+i}`));};$('#listenAyah').onclick=()=>selectedAyah&&playKeys([selectedAyah]);$('#copyAyah').onclick=copyAyah;$('#audioClose').onclick=stopAudio;$('#audioToggle').onclick=()=>{let a=$('#quranAudio');a.paused?a.play():a.pause();};$('#skipForward').onclick=()=>{if(playIndex<playQueue.length-1)loadAudio(playQueue[++playIndex]);};$('#skipBack').onclick=()=>{if(playIndex>0)loadAudio(playQueue[--playIndex]);};
let audio=$('#quranAudio');audio.ontimeupdate=e=>$('#audioProgress').style.width=`${(e.target.currentTime/e.target.duration||0)*100}%`;audio.onplay=()=>$('#audioToggle').textContent='❚❚';audio.onpause=()=>$('#audioToggle').textContent='▶';audio.onended=()=>playIndex<playQueue.length-1?loadAudio(playQueue[++playIndex]):stopAudio();
pageSurface.addEventListener('touchstart',e=>{if(e.touches.length===1)gesture={startX:e.touches[0].clientX,startY:e.touches[0].clientY,width:pageSurface.clientWidth,target:null};},{passive:true});pageSurface.addEventListener('touchmove',e=>{if(!gesture||e.touches.length!==1)return;let raw=e.touches[0].clientX-gesture.startX;if(Math.abs(raw)<Math.abs(e.touches[0].clientY-gesture.startY))return;e.preventDefault();let d=Math.max(-gesture.width,Math.min(gesture.width,raw)),dir=d>0?1:-1,target=currentPage+dir;if(target<1||target>604)return;Object.assign(gesture,{delta:d,direction:dir,target});if(gesture.previewTarget!==target){preview.src=imgURL(target);preview.classList.add('visible');gesture.previewTarget=target;}pageElement.classList.add('is-dragging');image.style.transform=`translateX(${d}px)`;preview.style.transform=`translateX(${dir>0?d-gesture.width:d+gesture.width}px)`;},{passive:false});pageSurface.addEventListener('touchend',e=>{if(gesture?.target)settleSwipe();else if(gesture){let t=e.changedTouches[0];if(Math.abs(t.clientX-gesture.startX)<12&&Math.abs(t.clientY-gesture.startY)<12)selectAyah(t.clientY-pageElement.getBoundingClientRect().top);else resetSwipe();}},{passive:true});pageSurface.addEventListener('touchcancel',resetSwipe,{passive:true});
['gesturestart','gesturechange','gestureend','dblclick'].forEach(n=>document.addEventListener(n,e=>e.preventDefault(),{passive:false}));document.addEventListener('touchmove',e=>{if(e.touches.length>1)e.preventDefault();},{passive:false});
let quranText='';fetch('quran.txt').then(r=>r.ok?r.text():'').then(t=>quranText=t).catch(()=>{});
async function copyAyah(){if(!selectedAyah)return;let verse=PAGE_MAP[currentPage-1].verses.find(v=>v[0]===selectedAyah),text=verse&&quranText?quranText.slice(verse[1],verse[2]).trim():'';try{await navigator.clipboard.writeText(text||`سورة ${SURAH_NAMES[selectedAyah.split(':')[0]]}، الآية ${selectedAyah.split(':')[1]}`);toast(text?'تم نسخ الآية.':'تم نسخ مرجع الآية.');}catch{toast('تعذر النسخ من هذا المتصفح.');}}
function loadAudio(k){let a=$('#quranAudio');updateAudio();a.src=sourceAudio(k);a.play().catch(()=>toast('تعذر تشغيل الصوت حالياً.'));}

/* طبقة اختيار دقيقة: مضلعات آيات المصحف، مطابقة لصفحات 604. */
let coordinatePage=0, audioSession=false;
function clearAyahSelection(){selectedAyah=null;$('#ayahSelection').hidden=true;document.querySelectorAll('.ayah-region.active,.ayah-region.audio-active').forEach(p=>p.classList.remove('active','audio-active'));}
function svgPath(points){const value=String(points).trim();if(/^[Mm]/.test(value))return value;const pairs=value.match(/-?\d+(?:\.\d+)?,-?\d+(?:\.\d+)?/g)||[];return pairs.length?`M ${pairs.join(' L ')} Z`:'';}
async function loadAyahCoordinates(page=currentPage){const layer=$('#ayahLayer');if(coordinatePage===page&&layer.childElementCount)return;coordinatePage=0;layer.replaceChildren();try{const file=`ayah-coordinates/${String(page).padStart(3,'0')}.json`,url=`${STORAGE}${encodeURIComponent(file)}?alt=media`,data=await fetch(url).then(r=>{if(!r.ok)throw Error();return r.json();});if(page!==currentPage)return;for(const ayah of data){const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',svgPath(ayah.polygon));path.setAttribute('fill-rule','evenodd');path.classList.add('ayah-region');path.dataset.key=`${ayah.surahNumber}:${ayah.ayahNumber}`;path.dataset.x=ayah.x;path.dataset.y=ayah.y;layer.append(path);}coordinatePage=page;if(audioSession&&playQueue[playIndex])showAudioAyah(playQueue[playIndex]);}catch{coordinatePage=0;toast('تعذر تحميل خريطة تحديد الآيات.');}}
function showActionAt(path){const layer=$('#ayahLayer').getBoundingClientRect(),box=$('#ayahSelection'),x=layer.left+(+path.dataset.x/345)*layer.width,y=layer.top+(+path.dataset.y/550)*layer.height,readerBox=pageElement.getBoundingClientRect();box.style.left=`${Math.max(32,Math.min(pageElement.clientWidth-32,x-readerBox.left))}px`;box.style.top=`${Math.max(58,y-readerBox.top-8)}px`;box.hidden=false;}
function selectExactAyah(path){if(audioSession)return;if(selectedAyah){clearAyahSelection();return;}selectedAyah=path.dataset.key;path.classList.add('active');showActionAt(path);}
function showAudioAyah(key){document.querySelectorAll('.ayah-region.active,.ayah-region.audio-active').forEach(p=>p.classList.remove('active','audio-active'));const path=document.querySelector(`.ayah-region[data-key="${key}"]`);if(path)path.classList.add('audio-active');}
async function navigateToAyah(key){const page=PAGE_MAP.findIndex(p=>p.verses.some(v=>v[0]===key))+1;if(page&&page!==currentPage){currentPage=page;renderPage(false);}await loadAyahCoordinates(currentPage);showAudioAyah(key);}
function renderPage(loader=false){clearAyahSelection();updateInfo();if(loader)showLoader('جاري الانتقال',`يتم تجهيز الصفحة ${nf.format(currentPage)} من المصحف الشريف`,100,'لحظات قليلة');const imageReady=new Promise(resolve=>{const done=()=>{hideLoading();resolve();};image.addEventListener('load',done,{once:true});image.addEventListener('error',()=>{hideLoading();toast('تعذر تحميل الصفحة.');resolve();},{once:true});image.src=imgURL(currentPage);if(image.complete&&image.naturalWidth)done();});return Promise.all([imageReady,loadAyahCoordinates(currentPage)]);}
async function loadAudio(key){audioSession=true;showLoader('جاري الانتقال',`يتم تجهيز سورة ${SURAH_NAMES[key.split(':')[0]]} والآية ${nf.format(key.split(':')[1])}`,100,'لحظات قليلة');await navigateToAyah(key);hideLoading();const a=$('#quranAudio');updateAudio();a.src=sourceAudio(key);a.play().catch(()=>toast('تعذر تشغيل الصوت حالياً.'));}
function stopAudio(){const a=$('#quranAudio');a.pause();a.removeAttribute('src');a.load();playQueue=[];audioSession=false;clearAyahSelection();$('#audioPlayer').classList.add('hidden');}
$('#ayahLayer').addEventListener('touchstart',e=>e.stopPropagation(),{passive:true});$('#ayahLayer').addEventListener('touchmove',e=>e.stopPropagation(),{passive:true});$('#ayahLayer').addEventListener('touchend',e=>e.stopPropagation(),{passive:true});$('#ayahLayer').addEventListener('click',e=>{e.stopPropagation();const path=e.target.closest('.ayah-region');if(path)selectExactAyah(path);});
/* تلتقط الصفحة السحب قبل طبقة الآيات؛ الضغطة القصيرة تظل للآية وحدها. */
let overlaySwipe=null;
pageSurface.addEventListener('touchstart',e=>{if(e.touches.length!==1)return;overlaySwipe={x:e.touches[0].clientX,y:e.touches[0].clientY,width:pageSurface.clientWidth,moved:false};},{capture:true,passive:true});
pageSurface.addEventListener('touchmove',e=>{if(!overlaySwipe||e.touches.length!==1)return;const dx=e.touches[0].clientX-overlaySwipe.x,dy=e.touches[0].clientY-overlaySwipe.y;if(Math.abs(dx)<12||Math.abs(dx)<=Math.abs(dy))return;overlaySwipe.moved=true;e.preventDefault();const direction=dx>0?1:-1,target=currentPage+direction;if(target<1||target>604)return;const delta=Math.max(-overlaySwipe.width,Math.min(overlaySwipe.width,dx));if(overlaySwipe.target!==target){preview.src=imgURL(target);preview.classList.add('visible');overlaySwipe.target=target;}pageElement.classList.add('is-dragging');image.style.transform=`translateX(${delta}px)`;preview.style.transform=`translateX(${direction>0?delta-overlaySwipe.width:delta+overlaySwipe.width}px)`;overlaySwipe.delta=delta;overlaySwipe.direction=direction;},{capture:true,passive:false});
pageSurface.addEventListener('touchend',()=>{if(!overlaySwipe)return;const swipe=overlaySwipe;overlaySwipe=null;if(!swipe.moved||!swipe.target)return;if(Math.abs(swipe.delta)<=swipe.width*.18){resetSwipe();return;}pageElement.classList.remove('is-dragging');image.style.transform=`translateX(${swipe.direction*swipe.width}px)`;preview.style.transform='translateX(0)';setTimeout(()=>{currentPage=swipe.target;image.src=preview.src;updateInfo();clearAyahSelection();loadAyahCoordinates(currentPage);resetSwipe();},285);},{capture:true,passive:true});
image.addEventListener('load',()=>loadAyahCoordinates(currentPage));
/* يمنع التقسيم التخميني القديم تماماً؛ كل اختيار يتم عبر مضلع الآية فقط. */
function selectAyah(){if(audioSession)return;if(selectedAyah)clearAyahSelection();}
